/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CertificateRegistryInterface extends Interface {
    getFunction(nameOrSignature: "certificates" | "registerCertificate" | "revokeCertificate" | "verifyCertificate"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateRegistered" | "CertificateRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'certificates', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'registerCertificate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'revokeCertificate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyCertificate', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'certificates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCertificate', data: BytesLike): Result;
  }

  
    export namespace CertificateRegisteredEvent {
      export type InputTuple = [certificateHash: BytesLike, issuer: AddressLike, issuedAt: BigNumberish];
      export type OutputTuple = [certificateHash: string, issuer: string, issuedAt: bigint];
      export interface OutputObject {certificateHash: string, issuer: string, issuedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CertificateRevokedEvent {
      export type InputTuple = [certificateHash: BytesLike];
      export type OutputTuple = [certificateHash: string];
      export interface OutputObject {certificateHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CertificateRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): CertificateRegistry;
    waitForDeployment(): Promise<this>;

    interface: CertificateRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    certificates: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, boolean] & {certificateHash: string, issuer: string, issuedAt: bigint, revoked: boolean }],
      'view'
    >
    

    
    registerCertificate: TypedContractMethod<
      [_certificateHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeCertificate: TypedContractMethod<
      [_certificateHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyCertificate: TypedContractMethod<
      [_certificateHash: BytesLike, ],
      [[boolean, string, bigint, boolean] & {exists: boolean, issuer: string, issuedAt: bigint, revoked: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'certificates'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, boolean] & {certificateHash: string, issuer: string, issuedAt: bigint, revoked: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'registerCertificate'): TypedContractMethod<
      [_certificateHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeCertificate'): TypedContractMethod<
      [_certificateHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyCertificate'): TypedContractMethod<
      [_certificateHash: BytesLike, ],
      [[boolean, string, bigint, boolean] & {exists: boolean, issuer: string, issuedAt: bigint, revoked: boolean }],
      'view'
    >;

    getEvent(key: 'CertificateRegistered'): TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
getEvent(key: 'CertificateRevoked'): TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;

    filters: {
      
      'CertificateRegistered(bytes32,address,uint256)': TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
      CertificateRegistered: TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
    

      'CertificateRevoked(bytes32)': TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
      CertificateRevoked: TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
    
    };
  }