/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificateRegistry } from './CertificateRegistry.js';
export type { EthereumDIDRegistry } from './EthereumDIDRegistry.js';
export * as factories from './factories/index.js';
export { CertificateRegistry__factory } from './factories/CertificateRegistry__factory.js';
export { EthereumDIDRegistry__factory } from './factories/EthereumDIDRegistry__factory.js';