/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CertificateRegistry__factory } from './CertificateRegistry__factory.js';
export { EthereumDIDRegistry__factory } from './EthereumDIDRegistry__factory.js';